force-app/main/default/objects/JobSeeker__c/JobSeeker__c.object-meta.xml
<CustomObject>
    <labels>JobSeeker</labels>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <labels>Number</labels>
        <type>AutoNumber</type>
    </nameField>
    <plurallabels>JobSeekers</plurallabels>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobSeeker__c/fields/Background__c.field-meta.xml
<CustomField>
    <fullName>Background__c</fullName>
    <labels>Background</labels>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/JobSeeker__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <labels>Email</labels>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/JobSeeker__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <labels>FirstName</labels>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JobSeeker__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <labels>LastName</labels>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JobSeeker__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <labels>Phone</labels>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/JobSeeker__c/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <labels>Specialization</labels>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JobSeekerConsoleController.cls
public without sharing class JobSeekerConsoleController {

    @AuraEnabled(cacheable=true)
    public static JobSeeker__c getJobSeeker(String userId) {       
        List<JobSeeker__c> jobSeekers = new List<JobSeeker__c>(
            [
                SELECT Specialization__c, Phone__c, Background__c, FirstName__c, LastName__c, Email__c 
                FROM JobSeeker__c 
                WHERE CreatedById = :userId
                LIMIT 1
            ]
        );      
        if (!jobSeekers.isEmpty()) {
            return jobSeekers[0];
        } else {
            return null;
        }        
    }

    @AuraEnabled
    public static Boolean deleteJobSeeker(String jobSeekerId) {       
        try {
            delete [Select Id FROM JobSeeker__c WHERE Id = :jobSeekerId];
            return true;
        } catch (DmlException e) {
            ErrorLoger__c errorLoger = new ErrorLoger__c(
                Message__c = (String)e.getMessage(),
                Cause__c = String.valueOf(e.getCause())
            );
            insert errorLoger;
            return false;
        }        
    }

}