force-app/main/default/objects/JobSeeker__c/JobSeeker__c.object-meta.xml
<CustomObject>
    <labels>JobSeeker</labels>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <labels>Number</labels>
        <type>AutoNumber</type>
    </nameField>
    <plurallabels>JobSeekers</plurallabels>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobSeeker__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <labels>Email</labels>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/JobSeeker__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <labels>LastName</labels>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JobSeekerConsoleControllerTest.cls
@isTest
private with sharing class JobSeekerConsoleControllerTest {
    
    @TestSetup
    static void makeData() {
        JobSeeker__c jobSeeker = new JobSeeker__c();
        jobSeeker.LastName__c = 'test';
        jobSeeker.Email__c = 'test@were.here';
        insert jobSeeker;
    }
    
    @isTest
    private static void getJobSeekerTest() {
        Id currentUser = UserInfo.getUserId();
        test.startTest();
        JobSeeker__c jobSeeker = JobSeekerConsoleController.getJobSeeker(currentUser);
        test.stopTest();       
        System.assert(jobSeeker != null);
    }

    @isTest
    private static void deleteJobSeekerTest() {
        JobSeeker__c jobSeeker = [SELECT Id FROM JobSeeker__c LIMIT 1];
        test.startTest();
        Boolean result = JobSeekerConsoleController.deleteJobSeeker(jobSeeker.Id);
        test.stopTest();     
        System.assert(result);
    }

}